services:
  weathered:
    build:
      context: .
      dockerfile: weathered.dockerfile

    container_name: weathered-app
    restart: unless-stopped
    privileged: true

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      
    environment:
      - DISPLAY=${DISPLAY}

    networks:
      - weathered-net
    
  llama-server:
    build:
      context: .
      dockerfile: llama.dockerfile
    
    container_name: llama-server-api
    restart: unless-stopped
    
    ports:
      - "8080:8080"
    networks:
      - weathered-net

networks:
  weathered-net:
    driver: bridge
